name: Run Trivy security checks

on:
  push:
    branches: [main]
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Manual Trivy Setup
      uses: aquasecurity/setup-trivy@v0.2.0
      with:
        cache: true
        version: v0.57.1

    - name: Run Trivy vulnerability scanner in fs mode (GitHub Action)
      id: trivy
      uses: aquasecurity/trivy-action@0.29.0
      continue-on-error: true
      with:
        scan-type: 'fs'
        scan-ref: './'
        skip-setup-trivy: true
        output: trivy.txt

    - name: Publish Trivy Output to Summary
      run: |
        if [[ -s trivy.txt ]]; then
        {
            echo "### Security Output"
            echo "<details><summary>Click to expand</summary>"
            echo ""
            echo '```text'
            cat trivy.txt
            echo '```'
            echo "</details>"
        } >> $GITHUB_STEP_SUMMARY
        else
        echo "No vulnerabilities found." >> $GITHUB_STEP_SUMMARY